"""Spin-weighted spheroidal harmonics (s = -2) at the equator, by spectral expansion.

Used by kerrflux.py (and check_odd_BRTV.py) for the separation constant lambda and for
S(pi/2), S'(pi/2), S''(pi/2) of the mode (l, m) with spheroidicity gamma = a omega.

Conventions: those of the Toolkit's SpinWeightedSpheroidalHarmonics package. The angular
equation is (1/sin) d/dtheta (sin dS/dtheta) + [gamma^2 cos^2 - m^2/sin^2 - 2 gamma s cos
- 2 m s cos/sin^2 - s^2 cot^2 + s + A] S = 0, with A = lambda - gamma^2 + 2 m gamma and
lambda the radial separation constant (SpinWeightedSpheroidalEigenvalue); S is normalised
to int |S|^2 dOmega = 1 and the sign is fixed by making the dominant spherical coefficient
positive.

Method: S is expanded in spin-weighted spherical harmonics _sY_{l'm}, l' = lmin ... lmin + N
(N = max(40, 3 gamma + 40)); the tridiagonal-squared matrix of the spheroidal operator is
diagonalised with numpy. The _sY_{l'm}(theta, 0) are generated by an upward recursion in
l' in mpmath (30 digits), starting from a Wigner d-matrix element, and the theta derivatives
at pi/2 come from five-point finite differences with step 1e-4 (in 30-digit arithmetic).
Running this file directly compares a few eigenvalues with Toolkit values.
"""
import numpy as np
import mpmath as mp


def a_coef(l, m, s):
    """Off-diagonal coefficient of cos(theta) in the spherical basis."""
    if l <= max(abs(m), abs(s)) or l == 0:
        return 0.0
    return np.sqrt((l*l - m*m)*(l*l - s*s))/(l*np.sqrt(4.0*l*l - 1.0))


def b_coef(l, m, s):
    """Diagonal coefficient of cos(theta) in the spherical basis."""
    return -m*s/(l*(l + 1.0))


def spheroidal(s, l, m, gam, N=None):
    """Spectral solution of the angular equation.

    Returns (lam, A, lvals, c): the radial separation constant lam, the angular eigenvalue A,
    the l' values of the basis and the expansion coefficients c."""
    lmin = max(abs(m), abs(s))
    if N is None:
        N = max(40, int(3*abs(gam)) + 40)
    lv = np.arange(lmin, lmin + N + 1)
    n = len(lv)
    C = np.zeros((n, n))           # matrix of cos(theta)
    for i, lp in enumerate(lv):
        C[i, i] = b_coef(lp, m, s)
        if i + 1 < n:
            C[i, i + 1] = a_coef(lp + 1, m, s)
            C[i + 1, i] = a_coef(lp + 1, m, s)
    E = (lv - s)*(lv + s + 1.0)
    M = np.diag(E) - gam*gam*(C @ C) + 2.0*gam*s*C
    w, v = np.linalg.eigh(M)
    k = l - lmin
    A = w[k]
    c = v[:, k]
    if c[k] < 0:                   # sign convention: dominant coefficient positive
        c = -c
    lam = A + gam*gam - 2.0*m*gam
    return lam, A, lv, c


def wigner_d(j, mp1, m2, beta):
    """Wigner small-d matrix element d^j_{mp1,m2}(beta) (Wikipedia convention), in mpmath."""
    tot = mp.mpf(0)
    for k in range(0, 2*j + 1):
        if j + m2 - k < 0 or j - k - mp1 < 0 or k - m2 + mp1 < 0:
            continue
        num = mp.sqrt(mp.factorial(j + mp1)*mp.factorial(j - mp1)*mp.factorial(j + m2)*mp.factorial(j - m2))
        den = mp.factorial(j + m2 - k)*mp.factorial(k)*mp.factorial(j - k - mp1)*mp.factorial(k - m2 + mp1)
        tot += (-1)**(k - m2 + mp1)*num/den*mp.cos(beta/2)**(2*j - 2*k + m2 - mp1)*mp.sin(beta/2)**(2*k - m2 + mp1)
    return tot


def sYlm_values(s, m, lmax, theta):
    """Values of _sY_{lm}(theta, 0) for l = lmin ... lmax by upward recursion in l (mpmath).
    Start: _sY_{lmin,m} = (-1)^s sqrt((2 lmin+1)/4pi) d^lmin_{m,-s}(theta)."""
    lmin = max(abs(m), abs(s))
    th = mp.mpf(theta)
    Y = {}
    Y[lmin] = (-1)**s*mp.sqrt((2*lmin + 1)/(4*mp.pi))*wigner_d(lmin, m, -s, th)
    Y[lmin - 1] = mp.mpf(0)
    ct = mp.cos(th)
    for l in range(lmin, lmax):
        al1 = mp.sqrt(((l + 1)**2 - m*m)*((l + 1)**2 - s*s))/((l + 1)*mp.sqrt(4*(l + 1)**2 - 1))
        al = mp.mpf(0) if l == lmin else mp.sqrt((l*l - m*m)*(l*l - s*s))/(l*mp.sqrt(4*l*l - 1))
        bl = mp.mpf(-m*s)/(l*(l + 1))
        Y[l + 1] = ((ct - bl)*Y[l] - al*Y[l - 1])/al1
    return [Y[l] for l in range(lmin, lmax + 1)]


def S_at_equator(s, l, m, gam, N=None, h=mp.mpf('1e-4'), dps=30):
    """S(pi/2), S'(pi/2), S''(pi/2) (theta derivatives), with int |S|^2 dOmega = 1.
    Returns (lam, S0, dS0, d2S0)."""
    mp.mp.dps = dps
    lam, A, lv, c = spheroidal(s, l, m, gam, N)
    lmax = int(lv[-1])
    vals = []
    for k in range(-2, 3):
        th = mp.pi/2 + k*h
        Yv = sYlm_values(s, m, lmax, th)
        vals.append(mp.fsum(mp.mpf(float(ci))*yi for ci, yi in zip(c, Yv)))
    f_m2, f_m1, f0, f1, f2 = vals
    S0 = f0
    dS0 = (f_m2 - 8*f_m1 + 8*f1 - f2)/(12*h)
    d2S0 = (-f_m2 + 16*f_m1 - 30*f0 + 16*f1 - f2)/(12*h*h)
    return lam, float(S0), float(dS0), float(d2S0)


if __name__ == "__main__":
    # (l, m, gamma) -> Toolkit SpinWeightedSpheroidalEigenvalue[-2, l, m, gamma]
    tests = [((20, 20, 6.0), 209.995773758), ((20, 19, 5.7), 228.911295415), ((20, 18, 5.4), 247.122752327),
             ((40, 40, 12.0), 816.943327351), ((40, 39, 11.7), 854.225325027), ((40, 38, 11.4), 890.896922357),
             ((80, 80, 24.0), 3207.03189392), ((80, 79, 23.7), 3281.31516593), ((80, 78, 23.4), 3355.02798694), ((10, 10, 0.0), 108.0)]
    for (l, m, g), ref in tests:
        lam, A, lv, c = spheroidal(-2, l, m, g)
        print(f"l={l} m={m} g={g}: lam={lam:.9f} ref={ref} diff={lam-ref:.2e}")
    lam, S0, dS0, d2S0 = S_at_equator(-2, 20, 20, 0.0)
    print("(20,20,0): |S0|^2 =", S0**2, " ref", 0.83782136*np.sqrt(20)/(2*np.pi**1.5), " dS0/S0 =", dS0/S0, " d2S0/S0 =", d2S0/S0, " (ref -16)")
